// -------------------------------------------------------------
// 
// File Name: C:\Users\Sechw\Documents\MATLAB\4440\codegen\yiqtorgb\hdlsrc\yiqtorgb_fixpt.v
// Created: 2014-12-04 01:24:54
// 
// Generated by MATLAB 8.2, MATLAB Coder 2.5 and HDL Coder 3.3
// 
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Design base rate: 1
// 
// 
// Clock Enable  Sample Time
// -- -------------------------------------------------------------
// ce_out        1
// -- -------------------------------------------------------------
// 
// 
// Output Signal                 Clock Enable  Sample Time
// -- -------------------------------------------------------------
// r                             ce_out        1
// g                             ce_out        1
// b                             ce_out        1
// -- -------------------------------------------------------------
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: yiqtorgb_fixpt
// Source Path: yiqtorgb_fixpt
// Hierarchy Level: 0
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module yiqtorgb_fixpt
          (
           clk,
           reset,
           ce,
           y,
           i,
           q,
           ce_out,
           r,
           g,
           b
          );


  input   clk;
  input   reset;
  input   ce;
  input   [7:0] y;  // ufix8
  input   [7:0] i;  // ufix8
  input   [7:0] q;  // ufix8
  output  ce_out;
  output  [7:0] r;  // ufix8
  output  [7:0] g;  // ufix8
  output  [7:0] b;  // ufix8


  wire enb;
  wire [8:0] yiqtorgb_fixpt_add_cast;  // ufix9
  wire [23:0] yiqtorgb_fixpt_add_cast_1;  // ufix24_En14
  wire [21:0] yiqtorgb_fixpt_mul_temp;  // ufix22_En14
  wire [23:0] yiqtorgb_fixpt_add_cast_2;  // ufix24_En14
  wire [23:0] yiqtorgb_fixpt_add_temp;  // ufix24_En14
  wire [24:0] yiqtorgb_fixpt_add_cast_3;  // ufix25_En14
  wire [21:0] yiqtorgb_fixpt_mul_temp_1;  // ufix22_En14
  wire [24:0] yiqtorgb_fixpt_add_cast_4;  // ufix25_En14
  wire [24:0] yiqtorgb_fixpt_add_temp_1;  // ufix25_En14
  wire [7:0] yiqtorgb_fixpt_cast;  // uint8
  wire [8:0] yiqtorgb_fixpt_sub_cast;  // ufix9
  wire signed [25:0] yiqtorgb_fixpt_sub_cast_1;  // sfix26_En15
  wire [21:0] yiqtorgb_fixpt_mul_temp_2;  // ufix22_En15
  wire signed [25:0] yiqtorgb_fixpt_sub_cast_2;  // sfix26_En15
  wire signed [25:0] yiqtorgb_fixpt_sub_temp;  // sfix26_En15
  wire [24:0] yiqtorgb_fixpt_sub_cast_3;  // ufix25_En15
  wire signed [26:0] yiqtorgb_fixpt_sub_cast_4;  // sfix27_En15
  wire [21:0] yiqtorgb_fixpt_mul_temp_3;  // ufix22_En14
  wire signed [26:0] yiqtorgb_fixpt_sub_cast_5;  // sfix27_En15
  wire signed [26:0] yiqtorgb_fixpt_sub_temp_1;  // sfix27_En15
  wire [7:0] yiqtorgb_fixpt_cast_1;  // uint8
  wire [8:0] yiqtorgb_fixpt_sub_cast_6;  // ufix9
  wire signed [23:0] yiqtorgb_fixpt_sub_cast_7;  // sfix24_En13
  wire [21:0] yiqtorgb_fixpt_mul_temp_4;  // ufix22_En13
  wire signed [23:0] yiqtorgb_fixpt_sub_cast_8;  // sfix24_En13
  wire signed [23:0] yiqtorgb_fixpt_sub_temp_2;  // sfix24_En13
  wire [22:0] yiqtorgb_fixpt_add_cast_5;  // ufix23_En13
  wire [23:0] yiqtorgb_fixpt_add_cast_6;  // ufix24_En13
  wire [21:0] yiqtorgb_fixpt_mul_temp_5;  // ufix22_En13
  wire [23:0] yiqtorgb_fixpt_add_cast_7;  // ufix24_En13
  wire [23:0] yiqtorgb_fixpt_add_temp_2;  // ufix24_En13
  wire [7:0] yiqtorgb_fixpt_cast_2;  // uint8


  assign enb = ce;

  //HDL code generation from MATLAB function: yiqtorgb_fixpt
  //%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
  //                                                                          %
  //       Generated by MATLAB 8.2, MATLAB Coder 2.5 and HDL Coder 3.3        %
  //                                                                          %
  //%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
  //'yiqtorgb_fixpt:9' fm = fimath('RoundingMethod', 'Floor', 'OverflowAction', 'Saturate', 'ProductMode', 'FullPrecision', 'SumMode', 'FullPrecision');
  //'yiqtorgb_fixpt:10' r = fi(uint8( fi(1, 0, 1, 0)*y + fi(0.956, 0, 14, 14)*i + fi(0.621, 0, 14, 14)*q ), 0, 8, 0, fm);
  //'yiqtorgb_fixpt:11' g = fi(uint8( fi(1, 0, 1, 0, fm)*y - fi(0.272, 0, 14, 15, fm)*i - fi(0.647, 0, 14, 14, fm)*q ), 0, 8, 0, fm);
  //'yiqtorgb_fixpt:12' b = fi(uint8( fi(1, 0, 1, 0, fm)*y - fi(1.105, 0, 14, 13, fm)*i + fi(1.702, 0, 14, 13, fm)*q ), 0, 8, 0, fm);
  assign yiqtorgb_fixpt_add_cast = y;
  assign yiqtorgb_fixpt_add_cast_1 = {yiqtorgb_fixpt_add_cast, 14'b00000000000000};
  assign yiqtorgb_fixpt_mul_temp = 15663 * i;
  assign yiqtorgb_fixpt_add_cast_2 = yiqtorgb_fixpt_mul_temp;
  assign yiqtorgb_fixpt_add_temp = yiqtorgb_fixpt_add_cast_1 + yiqtorgb_fixpt_add_cast_2;
  assign yiqtorgb_fixpt_add_cast_3 = yiqtorgb_fixpt_add_temp;
  assign yiqtorgb_fixpt_mul_temp_1 = 10174 * q;
  assign yiqtorgb_fixpt_add_cast_4 = yiqtorgb_fixpt_mul_temp_1;
  assign yiqtorgb_fixpt_add_temp_1 = yiqtorgb_fixpt_add_cast_3 + yiqtorgb_fixpt_add_cast_4;
  assign yiqtorgb_fixpt_cast = ((yiqtorgb_fixpt_add_temp_1[24:22] != 3'b000) || ((yiqtorgb_fixpt_add_temp_1[24] == 1'b0) && (yiqtorgb_fixpt_add_temp_1[21:14] == 8'b11111111)) ? 8'b11111111 :
              yiqtorgb_fixpt_add_temp_1[21:14] + yiqtorgb_fixpt_add_temp_1[13]);
  assign r = yiqtorgb_fixpt_cast;
  assign yiqtorgb_fixpt_sub_cast = y;
  assign yiqtorgb_fixpt_sub_cast_1 = {yiqtorgb_fixpt_sub_cast, 15'b000000000000000};
  assign yiqtorgb_fixpt_mul_temp_2 = 8912 * i;
  assign yiqtorgb_fixpt_sub_cast_2 = yiqtorgb_fixpt_mul_temp_2;
  assign yiqtorgb_fixpt_sub_temp = yiqtorgb_fixpt_sub_cast_1 - yiqtorgb_fixpt_sub_cast_2;
  assign yiqtorgb_fixpt_sub_cast_3 = (yiqtorgb_fixpt_sub_temp[25] == 1'b1 ? 25'b0000000000000000000000000 :
              yiqtorgb_fixpt_sub_temp[24:0]);
  assign yiqtorgb_fixpt_sub_cast_4 = yiqtorgb_fixpt_sub_cast_3;
  assign yiqtorgb_fixpt_mul_temp_3 = 10600 * q;
  assign yiqtorgb_fixpt_sub_cast_5 = {yiqtorgb_fixpt_mul_temp_3, 1'b0};
  assign yiqtorgb_fixpt_sub_temp_1 = yiqtorgb_fixpt_sub_cast_4 - yiqtorgb_fixpt_sub_cast_5;
  assign yiqtorgb_fixpt_cast_1 = (((yiqtorgb_fixpt_sub_temp_1[26] == 1'b0) && (yiqtorgb_fixpt_sub_temp_1[25:23] != 3'b000)) || ((yiqtorgb_fixpt_sub_temp_1[26] == 1'b0) && (yiqtorgb_fixpt_sub_temp_1[22:15] == 8'b11111111)) ? 8'b11111111 :
              (yiqtorgb_fixpt_sub_temp_1[26] == 1'b1 ? 8'b00000000 :
              yiqtorgb_fixpt_sub_temp_1[22:15] + (yiqtorgb_fixpt_sub_temp_1[14] & (( ~ yiqtorgb_fixpt_sub_temp_1[26]) | (|yiqtorgb_fixpt_sub_temp_1[13:0])))));
  assign g = yiqtorgb_fixpt_cast_1;
  assign yiqtorgb_fixpt_sub_cast_6 = y;
  assign yiqtorgb_fixpt_sub_cast_7 = {yiqtorgb_fixpt_sub_cast_6, 13'b0000000000000};
  assign yiqtorgb_fixpt_mul_temp_4 = 9052 * i;
  assign yiqtorgb_fixpt_sub_cast_8 = yiqtorgb_fixpt_mul_temp_4;
  assign yiqtorgb_fixpt_sub_temp_2 = yiqtorgb_fixpt_sub_cast_7 - yiqtorgb_fixpt_sub_cast_8;
  assign yiqtorgb_fixpt_add_cast_5 = (yiqtorgb_fixpt_sub_temp_2[23] == 1'b1 ? 23'b00000000000000000000000 :
              yiqtorgb_fixpt_sub_temp_2[22:0]);
  assign yiqtorgb_fixpt_add_cast_6 = yiqtorgb_fixpt_add_cast_5;
  assign yiqtorgb_fixpt_mul_temp_5 = 13942 * q;
  assign yiqtorgb_fixpt_add_cast_7 = yiqtorgb_fixpt_mul_temp_5;
  assign yiqtorgb_fixpt_add_temp_2 = yiqtorgb_fixpt_add_cast_6 + yiqtorgb_fixpt_add_cast_7;
  assign yiqtorgb_fixpt_cast_2 = ((yiqtorgb_fixpt_add_temp_2[23:21] != 3'b000) || ((yiqtorgb_fixpt_add_temp_2[23] == 1'b0) && (yiqtorgb_fixpt_add_temp_2[20:13] == 8'b11111111)) ? 8'b11111111 :
              yiqtorgb_fixpt_add_temp_2[20:13] + yiqtorgb_fixpt_add_temp_2[12]);
  assign b = yiqtorgb_fixpt_cast_2;



  assign ce_out = ce;

endmodule  // yiqtorgb_fixpt

