%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                                                                          %
%       Generated by MATLAB 8.2, MATLAB Coder 2.5 and HDL Coder 3.3        %
%                                                                          %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function [h,s,v] = rgbtohsv_wrapper_fixpt(r,g,b)
    fm = fimath( 'RoundingMethod', 'Floor', 'OverflowAction', 'Saturate', 'ProductMode', 'FullPrecision', 'SumMode', 'FullPrecision' );
    r_in = fi( r, 0, 8, 0, fm );
    g_in = fi( g, 0, 8, 0, fm );
    b_in = fi( b, 0, 8, 0, fm );
    [h_out,s_out,v_out] = rgbtohsv_fixpt( r_in, g_in, b_in );
    h = uint8( h_out );
    s = uint8( s_out );
    v = uint8( v_out );
end
