%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                                                                          %
%       Generated by MATLAB 8.2, MATLAB Coder 2.5 and HDL Coder 3.3        %
%                                                                          %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%#codegen
function [r,g,b] = yiqtorgb_fixpt(y,i,q)

fm = fimath('RoundingMethod', 'Floor', 'OverflowAction', 'Saturate', 'ProductMode', 'FullPrecision', 'SumMode', 'FullPrecision');
r = fi(uint8( fi(1, 0, 1, 0)*y + fi(0.956, 0, 14, 14)*i + fi(0.621, 0, 14, 14)*q ), 0, 8, 0, fm);
g = fi(uint8( fi(1, 0, 1, 0, fm)*y - fi(0.272, 0, 14, 15, fm)*i - fi(0.647, 0, 14, 14, fm)*q ), 0, 8, 0, fm);
b = fi(uint8( fi(1, 0, 1, 0, fm)*y - fi(1.105, 0, 14, 13, fm)*i + fi(1.702, 0, 14, 13, fm)*q ), 0, 8, 0, fm);
end
