%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                                                                          %
%       Generated by MATLAB 8.2, MATLAB Coder 2.5 and HDL Coder 3.3        %
%                                                                          %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function [r,g,b] = yiqtorgb_wrapper_fixpt(y,i,q)
    fm = fimath( 'RoundingMethod', 'Floor', 'OverflowAction', 'Saturate', 'ProductMode', 'FullPrecision', 'SumMode', 'FullPrecision' );
    y_in = fi( y, 0, 8, 0, fm );
    i_in = fi( i, 0, 8, 0, fm );
    q_in = fi( q, 0, 8, 0, fm );
    [r_out,g_out,b_out] = yiqtorgb_fixpt( y_in, i_in, q_in );
    r = uint8( r_out );
    g = uint8( g_out );
    b = uint8( b_out );
end
