%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                                                                          %
%       Generated by MATLAB 8.2, MATLAB Coder 2.5 and HDL Coder 3.3        %
%                                                                          %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function [y,i,q] = rgbtoyiq_wrapper_fixpt(r,g,b)
    fm = fimath( 'RoundingMethod', 'Floor', 'OverflowAction', 'Saturate', 'ProductMode', 'FullPrecision', 'SumMode', 'FullPrecision' );
    r_in = fi( r, 0, 8, 0, fm );
    g_in = fi( g, 0, 8, 0, fm );
    b_in = fi( b, 0, 8, 0, fm );
    [y_out,i_out,q_out] = rgbtoyiq_fixpt( r_in, g_in, b_in );
    y = uint8( y_out );
    i = uint8( i_out );
    q = uint8( q_out );
end
