%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                                                                          %
%       Generated by MATLAB 8.2, MATLAB Coder 2.5 and HDL Coder 3.3        %
%                                                                          %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%#codegen
function [y,i,q] = rgbtoyiq_fixpt(r,g,b)

fm = fimath('RoundingMethod', 'Floor', 'OverflowAction', 'Saturate', 'ProductMode', 'FullPrecision', 'SumMode', 'FullPrecision');
y = fi(uint8( fi(0.2989, 0, 14, 15)*r + fi(0.5870, 0, 14, 14)*g + fi(0.1140, 0, 14, 17)*b ), 0, 8, 0, fm);
i = fi(uint8( fi(0.596, 0, 14, 14, fm)*r - fi(0.274, 0, 14, 15, fm)*g - fi(0.322, 0, 14, 15, fm)*b ), 0, 8, 0, fm);
q = fi(uint8( fi(0.211, 0, 14, 16, fm)*r - fi(0.523, 0, 14, 14, fm)*g + fi(0.312, 0, 14, 15, fm)*b ), 0, 8, 0, fm);
end
