%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                                                                          %
%       Generated by MATLAB 8.2, MATLAB Coder 2.5 and HDL Coder 3.3        %
%                                                                          %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function [x,y,z] = rgbtoxyz_wrapper_fixpt(r,g,b)
    fm = fimath( 'RoundingMethod', 'Floor', 'OverflowAction', 'Saturate', 'ProductMode', 'FullPrecision', 'SumMode', 'FullPrecision' );
    r_in = fi( r, 0, 8, 0, fm );
    g_in = fi( g, 0, 8, 0, fm );
    b_in = fi( b, 0, 8, 0, fm );
    [x_out,y_out,z_out] = rgbtoxyz_fixpt( r_in, g_in, b_in );
    x = uint8( x_out );
    y = uint8( y_out );
    z = uint8( z_out );
end
