%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                                                                          %
%       Generated by MATLAB 8.2, MATLAB Coder 2.5 and HDL Coder 3.3        %
%                                                                          %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%#codegen
function [x,y,z] = rgbtoxyz_fixpt(r,g,b)

fm = fimath('RoundingMethod', 'Floor', 'OverflowAction', 'Saturate', 'ProductMode', 'FullPrecision', 'SumMode', 'FullPrecision');
x = fi(uint8( fi(0.5767309, 0, 14, 14)*r + fi(0.1855540, 0, 14, 16)*g + fi(0.1881852, 0, 14, 16)*b ), 0, 8, 0, fm);
y = fi(uint8( fi(0.2973769, 0, 14, 15, fm)*r + fi(0.6273491, 0, 14, 14, fm)*g + fi(0.0752741, 0, 14, 17, fm)*b ), 0, 8, 0, fm);
z = fi(uint8( fi(0.0270343, 0, 14, 19, fm)*r + fi(0.0706872, 0, 14, 17, fm)*g + fi(0.9911085, 0, 14, 13, fm)*b ), 0, 8, 0, fm);
end
