%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                                                                          %
%       Generated by MATLAB 8.2, MATLAB Coder 2.5 and HDL Coder 3.3        %
%                                                                          %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function [r,g,b] = xyztorgb_wrapper_fixpt(x,y,z)
    fm = fimath( 'RoundingMethod', 'Floor', 'OverflowAction', 'Saturate', 'ProductMode', 'FullPrecision', 'SumMode', 'FullPrecision' );
    x_in = fi( x, 0, 8, 0, fm );
    y_in = fi( y, 0, 8, 0, fm );
    z_in = fi( z, 0, 8, 0, fm );
    [r_out,g_out,b_out] = xyztorgb_fixpt( x_in, y_in, z_in );
    r = uint8( r_out );
    g = uint8( g_out );
    b = uint8( b_out );
end
