%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%                                                                          %
%       Generated by MATLAB 8.2, MATLAB Coder 2.5 and HDL Coder 3.3        %
%                                                                          %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%#codegen
function [r,g,b] = xyztorgb_fixpt(x,y,z)

fm = fimath('RoundingMethod', 'Floor', 'OverflowAction', 'Saturate', 'ProductMode', 'FullPrecision', 'SumMode', 'FullPrecision');
r = fi(uint8( fi(2.0413690, 0, 14, 12)*x - fi(0.5649464, 0, 14, 14)*y - fi(0.3446944, 0, 14, 15)*z ), 0, 8, 0, fm);
g = fi(uint8( fi_uminus(x) + fi(1.8760108, 0, 14, 13, fm)*y + fi(0.0415560, 0, 14, 18, fm)*z ), 0, 8, 0, fm);
b = fi(uint8( fi(0.0134474, 0, 14, 20, fm)*x - fi(0.1183897, 0, 14, 17, fm)*y + fi(1.0154096, 0, 14, 13, fm)*z ), 0, 8, 0, fm);
end


function y = fi_uminus(a)
coder.inline( 'always' );
if isfi( a )
    nt = numerictype( a );
    fm = fimath( a );
    new_nt = numerictype( 1, nt.WordLength + 1, nt.FractionLength );
    y = -fi( a, new_nt, fm );
else
    y = -a;
end
end
