// -------------------------------------------------------------
// 
// File Name: C:\Users\Sechw\Documents\MATLAB\4440\codegen\xyztorgb\hdlsrc\xyztorgb_fixpt.v
// Created: 2014-12-09 12:00:13
// 
// Generated by MATLAB 8.2, MATLAB Coder 2.5 and HDL Coder 3.3
// 
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Design base rate: 1
// 
// 
// Clock Enable  Sample Time
// -- -------------------------------------------------------------
// ce_out        1
// -- -------------------------------------------------------------
// 
// 
// Output Signal                 Clock Enable  Sample Time
// -- -------------------------------------------------------------
// r                             ce_out        1
// g                             ce_out        1
// b                             ce_out        1
// -- -------------------------------------------------------------
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: xyztorgb_fixpt
// Source Path: xyztorgb_fixpt
// Hierarchy Level: 0
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module xyztorgb_fixpt
          (
           clk,
           reset,
           ce,
           x,
           y,
           z,
           ce_out,
           r,
           g,
           b
          );


  input   clk;
  input   reset;
  input   ce;
  input   [7:0] x;  // ufix8
  input   [7:0] y;  // ufix8
  input   [7:0] z;  // ufix8
  output  ce_out;
  output  [7:0] r;  // ufix8
  output  [7:0] g;  // ufix8
  output  [7:0] b;  // ufix8


  wire enb;
  wire [21:0] xyztorgb_fixpt_mul_temp;  // ufix22_En12
  wire signed [25:0] xyztorgb_fixpt_sub_cast;  // sfix26_En14
  wire [21:0] xyztorgb_fixpt_mul_temp_1;  // ufix22_En14
  wire signed [25:0] xyztorgb_fixpt_sub_cast_1;  // sfix26_En14
  wire signed [25:0] xyztorgb_fixpt_sub_temp;  // sfix26_En14
  wire [24:0] xyztorgb_fixpt_sub_cast_2;  // ufix25_En14
  wire signed [27:0] xyztorgb_fixpt_sub_cast_3;  // sfix28_En15
  wire [21:0] xyztorgb_fixpt_mul_temp_2;  // ufix22_En15
  wire signed [27:0] xyztorgb_fixpt_sub_cast_4;  // sfix28_En15
  wire signed [27:0] xyztorgb_fixpt_sub_temp_1;  // sfix28_En15
  wire [7:0] xyztorgb_fixpt_cast;  // uint8
  wire signed [8:0] xyztorgb_fixpt_add_cast;  // sfix9
  wire signed [22:0] xyztorgb_fixpt_add_cast_1;  // sfix23_En13
  wire signed [23:0] xyztorgb_fixpt_add_cast_2;  // sfix24_En13
  wire [21:0] xyztorgb_fixpt_mul_temp_3;  // ufix22_En13
  wire signed [22:0] xyztorgb_fixpt_add_cast_3;  // sfix23_En13
  wire signed [23:0] xyztorgb_fixpt_add_cast_4;  // sfix24_En13
  wire signed [23:0] xyztorgb_fixpt_add_temp;  // sfix24_En13
  wire signed [22:0] xyztorgb_fixpt_add_cast_5;  // sfix23_En13
  wire signed [28:0] xyztorgb_fixpt_add_cast_6;  // sfix29_En18
  wire [21:0] xyztorgb_fixpt_mul_temp_4;  // ufix22_En18
  wire signed [28:0] xyztorgb_fixpt_add_cast_7;  // sfix29_En18
  wire signed [28:0] xyztorgb_fixpt_add_temp_1;  // sfix29_En18
  wire [7:0] xyztorgb_fixpt_cast_1;  // uint8
  wire [21:0] xyztorgb_fixpt_mul_temp_5;  // ufix22_En20
  wire signed [26:0] xyztorgb_fixpt_sub_cast_5;  // sfix27_En20
  wire [21:0] xyztorgb_fixpt_mul_temp_6;  // ufix22_En17
  wire signed [26:0] xyztorgb_fixpt_sub_cast_6;  // sfix27_En20
  wire signed [26:0] xyztorgb_fixpt_sub_temp_2;  // sfix27_En20
  wire [25:0] xyztorgb_fixpt_add_cast_8;  // ufix26_En20
  wire [29:0] xyztorgb_fixpt_add_cast_9;  // ufix30_En20
  wire [21:0] xyztorgb_fixpt_mul_temp_7;  // ufix22_En13
  wire [29:0] xyztorgb_fixpt_add_cast_10;  // ufix30_En20
  wire [29:0] xyztorgb_fixpt_add_temp_2;  // ufix30_En20
  wire [7:0] xyztorgb_fixpt_cast_2;  // uint8


  assign enb = ce;

  //HDL code generation from MATLAB function: xyztorgb_fixpt
  //%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
  //                                                                          %
  //       Generated by MATLAB 8.2, MATLAB Coder 2.5 and HDL Coder 3.3        %
  //                                                                          %
  //%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
  //'xyztorgb_fixpt:9' fm = fimath('RoundingMethod', 'Floor', 'OverflowAction', 'Saturate', 'ProductMode', 'FullPrecision', 'SumMode', 'FullPrecision');
  //'xyztorgb_fixpt:10' r = fi(uint8( fi(2.0413690, 0, 14, 12)*x - fi(0.5649464, 0, 14, 14)*y - fi(0.3446944, 0, 14, 15)*z ), 0, 8, 0, fm);
  //'xyztorgb_fixpt:11' g = fi(uint8( fi_uminus(x) + fi(1.8760108, 0, 14, 13, fm)*y + fi(0.0415560, 0, 14, 18, fm)*z ), 0, 8, 0, fm);
  //'xyztorgb_fixpt:17' coder.inline( 'always' );
  //'xyztorgb_fixpt:18' if isfi( a )
  //'xyztorgb_fixpt:19' nt = numerictype( a );
  //'xyztorgb_fixpt:20' fm = fimath( a );
  //'xyztorgb_fixpt:21' new_nt = numerictype( 1, nt.WordLength + 1, nt.FractionLength );
  //'xyztorgb_fixpt:22' y = -fi( a, new_nt, fm );
  //'xyztorgb_fixpt:12' b = fi(uint8( fi(0.0134474, 0, 14, 20, fm)*x - fi(0.1183897, 0, 14, 17, fm)*y + fi(1.0154096, 0, 14, 13, fm)*z ), 0, 8, 0, fm);
  assign xyztorgb_fixpt_mul_temp = 8361 * x;
  assign xyztorgb_fixpt_sub_cast = {xyztorgb_fixpt_mul_temp, 2'b00};
  assign xyztorgb_fixpt_mul_temp_1 = 9256 * y;
  assign xyztorgb_fixpt_sub_cast_1 = xyztorgb_fixpt_mul_temp_1;
  assign xyztorgb_fixpt_sub_temp = xyztorgb_fixpt_sub_cast - xyztorgb_fixpt_sub_cast_1;
  assign xyztorgb_fixpt_sub_cast_2 = (xyztorgb_fixpt_sub_temp[25] == 1'b1 ? 25'b0000000000000000000000000 :
              xyztorgb_fixpt_sub_temp[24:0]);
  assign xyztorgb_fixpt_sub_cast_3 = {xyztorgb_fixpt_sub_cast_2, 1'b0};
  assign xyztorgb_fixpt_mul_temp_2 = 11295 * z;
  assign xyztorgb_fixpt_sub_cast_4 = xyztorgb_fixpt_mul_temp_2;
  assign xyztorgb_fixpt_sub_temp_1 = xyztorgb_fixpt_sub_cast_3 - xyztorgb_fixpt_sub_cast_4;
  assign xyztorgb_fixpt_cast = (((xyztorgb_fixpt_sub_temp_1[27] == 1'b0) && (xyztorgb_fixpt_sub_temp_1[26:23] != 4'b0000)) || ((xyztorgb_fixpt_sub_temp_1[27] == 1'b0) && (xyztorgb_fixpt_sub_temp_1[22:15] == 8'b11111111)) ? 8'b11111111 :
              (xyztorgb_fixpt_sub_temp_1[27] == 1'b1 ? 8'b00000000 :
              xyztorgb_fixpt_sub_temp_1[22:15] + (xyztorgb_fixpt_sub_temp_1[14] & (( ~ xyztorgb_fixpt_sub_temp_1[27]) | (|xyztorgb_fixpt_sub_temp_1[13:0])))));
  assign r = xyztorgb_fixpt_cast;
  assign xyztorgb_fixpt_add_cast =  - (x);
  assign xyztorgb_fixpt_add_cast_1 = {xyztorgb_fixpt_add_cast[8], {xyztorgb_fixpt_add_cast, 13'b0000000000000}};
  assign xyztorgb_fixpt_add_cast_2 = xyztorgb_fixpt_add_cast_1;
  assign xyztorgb_fixpt_mul_temp_3 = 15368 * y;
  assign xyztorgb_fixpt_add_cast_3 = xyztorgb_fixpt_mul_temp_3;
  assign xyztorgb_fixpt_add_cast_4 = xyztorgb_fixpt_add_cast_3;
  assign xyztorgb_fixpt_add_temp = xyztorgb_fixpt_add_cast_2 + xyztorgb_fixpt_add_cast_4;
  assign xyztorgb_fixpt_add_cast_5 = ((xyztorgb_fixpt_add_temp[23] == 1'b0) && (xyztorgb_fixpt_add_temp[22] != 1'b0) ? 23'sb01111111111111111111111 :
              ((xyztorgb_fixpt_add_temp[23] == 1'b1) && (xyztorgb_fixpt_add_temp[22] != 1'b1) ? 23'sb10000000000000000000000 :
              $signed(xyztorgb_fixpt_add_temp[22:0])));
  assign xyztorgb_fixpt_add_cast_6 = {xyztorgb_fixpt_add_cast_5[22], {xyztorgb_fixpt_add_cast_5, 5'b00000}};
  assign xyztorgb_fixpt_mul_temp_4 = 10893 * z;
  assign xyztorgb_fixpt_add_cast_7 = xyztorgb_fixpt_mul_temp_4;
  assign xyztorgb_fixpt_add_temp_1 = xyztorgb_fixpt_add_cast_6 + xyztorgb_fixpt_add_cast_7;
  assign xyztorgb_fixpt_cast_1 = (((xyztorgb_fixpt_add_temp_1[28] == 1'b0) && (xyztorgb_fixpt_add_temp_1[27:26] != 2'b00)) || ((xyztorgb_fixpt_add_temp_1[28] == 1'b0) && (xyztorgb_fixpt_add_temp_1[25:18] == 8'b11111111)) ? 8'b11111111 :
              (xyztorgb_fixpt_add_temp_1[28] == 1'b1 ? 8'b00000000 :
              xyztorgb_fixpt_add_temp_1[25:18] + (xyztorgb_fixpt_add_temp_1[17] & (( ~ xyztorgb_fixpt_add_temp_1[28]) | (|xyztorgb_fixpt_add_temp_1[16:0])))));
  assign g = xyztorgb_fixpt_cast_1;
  assign xyztorgb_fixpt_mul_temp_5 = 14100 * x;
  assign xyztorgb_fixpt_sub_cast_5 = xyztorgb_fixpt_mul_temp_5;
  assign xyztorgb_fixpt_mul_temp_6 = 15517 * y;
  assign xyztorgb_fixpt_sub_cast_6 = {xyztorgb_fixpt_mul_temp_6, 3'b000};
  assign xyztorgb_fixpt_sub_temp_2 = xyztorgb_fixpt_sub_cast_5 - xyztorgb_fixpt_sub_cast_6;
  assign xyztorgb_fixpt_add_cast_8 = (xyztorgb_fixpt_sub_temp_2[26] == 1'b1 ? 26'b00000000000000000000000000 :
              xyztorgb_fixpt_sub_temp_2[25:0]);
  assign xyztorgb_fixpt_add_cast_9 = xyztorgb_fixpt_add_cast_8;
  assign xyztorgb_fixpt_mul_temp_7 = 8318 * z;
  assign xyztorgb_fixpt_add_cast_10 = {xyztorgb_fixpt_mul_temp_7, 7'b0000000};
  assign xyztorgb_fixpt_add_temp_2 = xyztorgb_fixpt_add_cast_9 + xyztorgb_fixpt_add_cast_10;
  assign xyztorgb_fixpt_cast_2 = ((xyztorgb_fixpt_add_temp_2[29:28] != 2'b00) || ((xyztorgb_fixpt_add_temp_2[29] == 1'b0) && (xyztorgb_fixpt_add_temp_2[27:20] == 8'b11111111)) ? 8'b11111111 :
              xyztorgb_fixpt_add_temp_2[27:20] + xyztorgb_fixpt_add_temp_2[19]);
  assign b = xyztorgb_fixpt_cast_2;



  assign ce_out = ce;

endmodule  // xyztorgb_fixpt

