// -------------------------------------------------------------
// 
// File Name: C:\Users\Sechw\Documents\MATLAB\4440\codegen\rgbtoxyz\hdlsrc\rgbtoxyz_fixpt.v
// Created: 2014-12-04 16:26:43
// 
// Generated by MATLAB 8.2, MATLAB Coder 2.5 and HDL Coder 3.3
// 
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Design base rate: 1
// 
// 
// Clock Enable  Sample Time
// -- -------------------------------------------------------------
// ce_out        1
// -- -------------------------------------------------------------
// 
// 
// Output Signal                 Clock Enable  Sample Time
// -- -------------------------------------------------------------
// x                             ce_out        1
// y                             ce_out        1
// z                             ce_out        1
// -- -------------------------------------------------------------
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: rgbtoxyz_fixpt
// Source Path: rgbtoxyz_fixpt
// Hierarchy Level: 0
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module rgbtoxyz_fixpt
          (
           clk,
           reset,
           ce,
           r,
           g,
           b,
           ce_out,
           x,
           y,
           z
          );


  input   clk;
  input   reset;
  input   ce;
  input   [7:0] r;  // ufix8
  input   [7:0] g;  // ufix8
  input   [7:0] b;  // ufix8
  output  ce_out;
  output  [7:0] x;  // ufix8
  output  [7:0] y;  // ufix8
  output  [7:0] z;  // ufix8


  wire enb;
  wire [21:0] rgbtoxyz_fixpt_mul_temp;  // ufix22_En14
  wire [24:0] rgbtoxyz_fixpt_add_cast;  // ufix25_En16
  wire [21:0] rgbtoxyz_fixpt_mul_temp_1;  // ufix22_En16
  wire [24:0] rgbtoxyz_fixpt_add_cast_1;  // ufix25_En16
  wire [24:0] rgbtoxyz_fixpt_add_temp;  // ufix25_En16
  wire [25:0] rgbtoxyz_fixpt_add_cast_2;  // ufix26_En16
  wire [21:0] rgbtoxyz_fixpt_mul_temp_2;  // ufix22_En16
  wire [25:0] rgbtoxyz_fixpt_add_cast_3;  // ufix26_En16
  wire [25:0] rgbtoxyz_fixpt_add_temp_1;  // ufix26_En16
  wire [7:0] rgbtoxyz_fixpt_cast;  // uint8
  wire [21:0] rgbtoxyz_fixpt_mul_temp_3;  // ufix22_En15
  wire [23:0] rgbtoxyz_fixpt_add_cast_4;  // ufix24_En15
  wire [21:0] rgbtoxyz_fixpt_mul_temp_4;  // ufix22_En14
  wire [23:0] rgbtoxyz_fixpt_add_cast_5;  // ufix24_En15
  wire [23:0] rgbtoxyz_fixpt_add_temp_2;  // ufix24_En15
  wire [26:0] rgbtoxyz_fixpt_add_cast_6;  // ufix27_En17
  wire [21:0] rgbtoxyz_fixpt_mul_temp_5;  // ufix22_En17
  wire [26:0] rgbtoxyz_fixpt_add_cast_7;  // ufix27_En17
  wire [26:0] rgbtoxyz_fixpt_add_temp_3;  // ufix27_En17
  wire [7:0] rgbtoxyz_fixpt_cast_1;  // uint8
  wire [21:0] rgbtoxyz_fixpt_mul_temp_6;  // ufix22_En19
  wire [24:0] rgbtoxyz_fixpt_add_cast_8;  // ufix25_En19
  wire [21:0] rgbtoxyz_fixpt_mul_temp_7;  // ufix22_En17
  wire [24:0] rgbtoxyz_fixpt_add_cast_9;  // ufix25_En19
  wire [24:0] rgbtoxyz_fixpt_add_temp_4;  // ufix25_En19
  wire [28:0] rgbtoxyz_fixpt_add_cast_10;  // ufix29_En19
  wire [21:0] rgbtoxyz_fixpt_mul_temp_8;  // ufix22_En13
  wire [28:0] rgbtoxyz_fixpt_add_cast_11;  // ufix29_En19
  wire [28:0] rgbtoxyz_fixpt_add_temp_5;  // ufix29_En19
  wire [7:0] rgbtoxyz_fixpt_cast_2;  // uint8


  assign enb = ce;

  //HDL code generation from MATLAB function: rgbtoxyz_fixpt
  //%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
  //                                                                          %
  //       Generated by MATLAB 8.2, MATLAB Coder 2.5 and HDL Coder 3.3        %
  //                                                                          %
  //%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
  //'rgbtoxyz_fixpt:9' fm = fimath('RoundingMethod', 'Floor', 'OverflowAction', 'Saturate', 'ProductMode', 'FullPrecision', 'SumMode', 'FullPrecision');
  //'rgbtoxyz_fixpt:10' x = fi(uint8( fi(0.5767309, 0, 14, 14)*r + fi(0.1855540, 0, 14, 16)*g + fi(0.1881852, 0, 14, 16)*b ), 0, 8, 0, fm);
  //'rgbtoxyz_fixpt:11' y = fi(uint8( fi(0.2973769, 0, 14, 15, fm)*r + fi(0.6273491, 0, 14, 14, fm)*g + fi(0.0752741, 0, 14, 17, fm)*b ), 0, 8, 0, fm);
  //'rgbtoxyz_fixpt:12' z = fi(uint8( fi(0.0270343, 0, 14, 19, fm)*r + fi(0.0706872, 0, 14, 17, fm)*g + fi(0.9911085, 0, 14, 13, fm)*b ), 0, 8, 0, fm);
  assign rgbtoxyz_fixpt_mul_temp = 9449 * r;
  assign rgbtoxyz_fixpt_add_cast = {rgbtoxyz_fixpt_mul_temp, 2'b00};
  assign rgbtoxyz_fixpt_mul_temp_1 = 12160 * g;
  assign rgbtoxyz_fixpt_add_cast_1 = rgbtoxyz_fixpt_mul_temp_1;
  assign rgbtoxyz_fixpt_add_temp = rgbtoxyz_fixpt_add_cast + rgbtoxyz_fixpt_add_cast_1;
  assign rgbtoxyz_fixpt_add_cast_2 = rgbtoxyz_fixpt_add_temp;
  assign rgbtoxyz_fixpt_mul_temp_2 = 12333 * b;
  assign rgbtoxyz_fixpt_add_cast_3 = rgbtoxyz_fixpt_mul_temp_2;
  assign rgbtoxyz_fixpt_add_temp_1 = rgbtoxyz_fixpt_add_cast_2 + rgbtoxyz_fixpt_add_cast_3;
  assign rgbtoxyz_fixpt_cast = ((rgbtoxyz_fixpt_add_temp_1[25:24] != 2'b00) || ((rgbtoxyz_fixpt_add_temp_1[25] == 1'b0) && (rgbtoxyz_fixpt_add_temp_1[23:16] == 8'b11111111)) ? 8'b11111111 :
              rgbtoxyz_fixpt_add_temp_1[23:16] + rgbtoxyz_fixpt_add_temp_1[15]);
  assign x = rgbtoxyz_fixpt_cast;
  assign rgbtoxyz_fixpt_mul_temp_3 = 9744 * r;
  assign rgbtoxyz_fixpt_add_cast_4 = rgbtoxyz_fixpt_mul_temp_3;
  assign rgbtoxyz_fixpt_mul_temp_4 = 10278 * g;
  assign rgbtoxyz_fixpt_add_cast_5 = {rgbtoxyz_fixpt_mul_temp_4, 1'b0};
  assign rgbtoxyz_fixpt_add_temp_2 = rgbtoxyz_fixpt_add_cast_4 + rgbtoxyz_fixpt_add_cast_5;
  assign rgbtoxyz_fixpt_add_cast_6 = {rgbtoxyz_fixpt_add_temp_2, 2'b00};
  assign rgbtoxyz_fixpt_mul_temp_5 = 9866 * b;
  assign rgbtoxyz_fixpt_add_cast_7 = rgbtoxyz_fixpt_mul_temp_5;
  assign rgbtoxyz_fixpt_add_temp_3 = rgbtoxyz_fixpt_add_cast_6 + rgbtoxyz_fixpt_add_cast_7;
  assign rgbtoxyz_fixpt_cast_1 = ((rgbtoxyz_fixpt_add_temp_3[26:25] != 2'b00) || ((rgbtoxyz_fixpt_add_temp_3[26] == 1'b0) && (rgbtoxyz_fixpt_add_temp_3[24:17] == 8'b11111111)) ? 8'b11111111 :
              rgbtoxyz_fixpt_add_temp_3[24:17] + rgbtoxyz_fixpt_add_temp_3[16]);
  assign y = rgbtoxyz_fixpt_cast_1;
  assign rgbtoxyz_fixpt_mul_temp_6 = 14173 * r;
  assign rgbtoxyz_fixpt_add_cast_8 = rgbtoxyz_fixpt_mul_temp_6;
  assign rgbtoxyz_fixpt_mul_temp_7 = 9265 * g;
  assign rgbtoxyz_fixpt_add_cast_9 = {rgbtoxyz_fixpt_mul_temp_7, 2'b00};
  assign rgbtoxyz_fixpt_add_temp_4 = rgbtoxyz_fixpt_add_cast_8 + rgbtoxyz_fixpt_add_cast_9;
  assign rgbtoxyz_fixpt_add_cast_10 = rgbtoxyz_fixpt_add_temp_4;
  assign rgbtoxyz_fixpt_mul_temp_8 = 8119 * b;
  assign rgbtoxyz_fixpt_add_cast_11 = {rgbtoxyz_fixpt_mul_temp_8, 6'b000000};
  assign rgbtoxyz_fixpt_add_temp_5 = rgbtoxyz_fixpt_add_cast_10 + rgbtoxyz_fixpt_add_cast_11;
  assign rgbtoxyz_fixpt_cast_2 = ((rgbtoxyz_fixpt_add_temp_5[28:27] != 2'b00) || ((rgbtoxyz_fixpt_add_temp_5[28] == 1'b0) && (rgbtoxyz_fixpt_add_temp_5[26:19] == 8'b11111111)) ? 8'b11111111 :
              rgbtoxyz_fixpt_add_temp_5[26:19] + rgbtoxyz_fixpt_add_temp_5[18]);
  assign z = rgbtoxyz_fixpt_cast_2;



  assign ce_out = ce;

endmodule  // rgbtoxyz_fixpt

